inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rspec

RSpec/PredicateMatcher:
  Enabled: false

AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - "bin/*"
