# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in maze_generator.gemspec
gemspec

gem 'fiddle'
gem 'rake'
gem 'rspec', '~> 3.0'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rspec'
gem 'simplecov', '~> 0.22'
